name: Ubuntu Terminal

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Setup
      run: |
        sudo apt update
        sudo apt install unzip openssh-server -y

    - name: Download latest ngrok
      run: |
        wget -O ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
        unzip ngrok.zip
        sudo mv ngrok /usr/local/bin
        chmod +x /usr/local/bin/ngrok

    - name: Start SSH and configure ngrok
      run: |
        echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
        echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
        echo "PermitEmptyPasswords no" | sudo tee -a /etc/ssh/sshd_config
        sudo service ssh start

        echo -e "root:Score-x" | sudo chpasswd
        sudo usermod -s /bin/bash root

        ngrok config add-authtoken 2xWnfOyRd1Zi5KaeMnvqsIziHLW_6PYhXB2qC9AKg6grTubJJ

        nohup ngrok tcp 22 --region ap > ngrok.log 2>&1 &
        sleep 15
        cat ngrok.log

    - name: Show SSH Info
      run: |
        for i in {1..10}; do
          SSH_INFO=$(curl -s http://127.0.0.1:4040/api/tunnels | grep -o 'tcp://[^"]*')
          if [ -n "$SSH_INFO" ]; then
            echo "====================================="
            echo "SSH Tunnel: $SSH_INFO"
            echo "Login with: ssh root@HOST -p PORT"
            echo "Password: Score-x"
            echo "====================================="
            break
          fi
          echo "Waiting for ngrok tunnel..."
          sleep 5
        done

        if [ -z "$SSH_INFO" ]; then
          echo "Failed to get ngrok tunnel."
          exit 1
        fi

    - name: Keep alive
      run: |
        echo "Terminal is now accessible. Keeping runner alive..."
        while true; do sleep 60; done
