name: Ubuntu Terminal

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Setup
      run: |
        sudo apt update
        sudo apt install unzip openssh-server -y

    - name: Download latest ngrok
      run: |
        wget -O ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
        unzip ngrok.zip
        sudo mv ngrok /usr/local/bin
        chmod +x /usr/local/bin/ngrok

    - name: Start SSH and configure ngrok
      run: |
        echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
        echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
        echo "PermitEmptyPasswords no" | sudo tee -a /etc/ssh/sshd_config
        sudo service ssh start

        echo -e "root:Score-x" | sudo chpasswd
        sudo usermod -s /bin/bash root

        ngrok config add-authtoken 2qiXwqE9lFYqe9NvvpTGZTj7F5h_2Wquuw8qRBApdFBQox56J
        nohup ngrok tcp 22 --region ap &>/dev/null &

    - name: Show SSH Info
      run: |
        sleep 10
        curl -s http://127.0.0.1:4040/api/tunnels | grep -o 'tcp://[^"]*'

    - name: Keep alive
      run: sleep infinity
