name: Free Terminal via GitHub Actions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # runs every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # keeps alive for 6 hours
    steps:
    - name: Set up Ngrok & SSH
      run: |
        sudo apt update
        sudo apt install -y openssh-server wget unzip
        echo "root:ScoreX123" | sudo chpasswd
        sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo service ssh restart

        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        ./ngrok authtoken 2qiXwqE9lFYqe9NvvpTGZTj7F5h_2Wquuw8qRBApdFBQox56J
        ./ngrok tcp 22 > ngrok.log &
        sleep 10
        echo "🔑 SSH Login Info:"
        cat ngrok.log
        sleep 3400  # keep alive
